name: Tests
on: [push, pull_request]
jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        django-version: ["django~=3.2", "django~=4.1", "django~=4.2"]
        optional-dependencies: ["optional-deps", "no-optional-deps"]
        exclude:
          - python-version: "3.7"
            django-version: "django~=4.1"
          - python-version: "3.7"
            django-version: "django~=4.2"
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
      DJANGO: ${{ matrix.django-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install "${{ matrix.django-version }}"
          pip install -e .[test]
      - name: Install optional dependencies
        if: matrix.optional-dependencies == 'optional-deps'
        run: pip install -e .[optional]
      - name: Run tests and generate coverage report
        run: coverage run
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON,DJANGO
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
